#ifndef __MyProject1SFMMainfram__
#define __MyProject1SFMMainfram__

/**
@file
Subclass of SFMMainfram, which is generated by wxFormBuilder.
*/

#include "sfmMainFram.h"
#include "sfmARhr.h"
/** Implementing SFMMainfram */
class MyProject1SFMMainfram : public SFMMainfram
{
protected:
	// Handlers for SFMMainfram events.
	void framCharPressed( wxKeyEvent& event );
	void framKeyPressed( wxKeyEvent& event );
	void framMouseClicked( wxMouseEvent& event );
	void OpenPlyFile( wxCommandEvent& event );
	void OpenCamCenter( wxCommandEvent& event );
	void ExitFunc( wxCommandEvent& event );
	  TestGLCanvas *m_canvas;
public:
	/** Constructor */
	MyProject1SFMMainfram( wxWindow* parent );
};

#endif // __MyProject1SFMMainfram__
